oursite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^zhilianzhaopin/',include('zhilianzhaopin.urls',namespace='zhilianzhaopin')),
    url(r'^$', views.home, name='home'),
]

zhilianzhaopin/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.zhilianzhaopin_show, name='zhilianzhaopin_show'),
    url(r'^jobs/(?P<p>[0-9]+)/$',views.JobMesView.as_view(),name='jobs'),
    url(r'^location_show/$',views.location_show,name='location_show'),
    url(r'^work_experience_show/$',views.work_experience_show,name='work_experience_show'),
    url(r'^education_show/$',views.education_show,name='education_show'),
    url(r'^wordcloud_show/$',views.wordcloud_show,name='wordcloud_show'),
    url(r'^work_detail/(?P<n>[0-9]+)/$',views.work_detail,name='work_detail'),
]

zhilianzhaopin/models.py
from django.db import models

# Create your models here.
class Jobs(models.Model):
    job_title = models.CharField('工作职位',max_length=20,null=True,blank=True)
    job_categories = models.CharField('职位性质',max_length=20,null=True,blank=True)
    wage1 = models.IntegerField('最低工资',null=True,blank=True)
    wage2 = models.IntegerField('最高工资',null=True,blank=True)
    location = models.CharField('地址',max_length=25,null=True,blank=True)
    work_experience = models.CharField('工作经验',max_length=10,null=True,blank=True)
    education = models.CharField('学历',max_length=10,null=True,blank=True)
    recruits_number = models.CharField('招聘人数',max_length=10,null=True,blank=True)
    company_name = models.CharField('公司名字',max_length=20,null=True,blank=True)
    company_type = models.CharField('公司类型',max_length=10,null=True,blank=True)
    company_size = models.CharField('公司规模',max_length=10,null=True,blank=True)
    company_address = models.CharField('公司详细地址',max_length=16,null=True,blank=True)
    welfare_pos = models.CharField('各种福利',max_length=100,null=True,blank=True)
    job_description = models.TextField('工作详情',null=True,blank=True)

    def __str__(self):
        return self.job_title

oursite/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'layouts/master_blade.html')

zhilianzhaopin/views.py
from django.shortcuts import render
import sqlite3
import pandas as pd
from pyecharts import Pie, Bar,WordCloud
from .models import Jobs
from django.views import View
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import JsonResponse
import json
import pymongo
import jieba
import re
# Create your views here.
def zhilianzhaopin_show(req):
    msg = req.POST.get('kw','')
    return render(req,'zhilianzhaopin/index.html',context={'msg':msg})


class JobMesView(View):
    def __init__(self):
        super(JobMesView,self).__init__()
        self.client = pymongo.MongoClient(host='106.12.40.6', port=27017)
        self.db = self.client.zhilianzhaopin
        self.collection = self.db.classify


    def search_city(self,city,jobs):
        if city=='全国':
            jobs = jobs
        else:
            jobs = jobs.filter(
                Q(location__icontains=city)
            )
        return jobs

    def search_wage(self,wage,jobs):
        if wage == '不限':
            jobs = jobs
        elif wage=='7k以下':
            jobs = jobs.filt全国er(
                Q(wage1__lt=7)
            )
        elif wage == '20k以上':

            jobs = jobs.filter(
                Q(wage2__gt=20)
            )
        else:
            wage_low = wage.split('-')[0].strip('k')
            wage_high = wage.split('-')[1].strip('k')
            jobs = jobs.filter((Q(wage1__lt=wage_low)&Q(wage2__gt=wage_low))|(Q(wage1__lt=wage_high)&Q(wage2__gt=wage_high)))
        return jobs

    def search_exp(self,exp,jobs):
        if exp == '工作经验' or exp == '不限':
            jobs = jobs
        else:
            jobs = jobs.filter(Q(work_experience__icontains=exp))
        return jobs

    def search_edu(self,edu,jobs):
        if edu == '学历要求' or edu == '不限':
            jobs = jobs
        else:
            jobs = jobs.filter(Q(education__icontains=edu))
        return jobs

    def search_keywords(self,search_keywords,jobs):
        if search_keywords.strip() == '':
            jobs = jobs
        else:
            jobs = jobs.filter(Q(job_title__icontains=search_keywords)|Q(job_description__icontains=search_keywords))
        return jobs

    def search_category(self,category,jobs):
        print(category)
        if category == '不限':
            return jobs
        k = self.collection.find({'category':category})
        id_list = []
        for i in k:
            id_list.append(i['_id'])
        print(id_list)

        jobs = jobs.filter(Q(id__in = id_list))
        return jobs

    def get(self,request,p=1):
        city = request.GET.get('city','全国').strip()
        wage = request.GET.get('wage','不限').strip()
        edu = request.GET.get('edu','学历要求').strip()
        exp = request.GET.get('years','工作经验').strip()
        category = request.GET.get('category', '不限').strip()
        search_keywords = request.GET.get('kw', '').strip()
        p = request.GET.get('page',1)
        jobs = Jobs.objects.all()
        jobs1 = self.search_city(city,jobs)
        jobs2 = self.search_keywords(search_keywords,jobs1)
        jobs3 = self.search_edu(edu,jobs2)
        jobs4 = self.search_exp(exp,jobs3)
        jobs5 = self.search_wage(wage,jobs4)
        jobs6 = self.search_category(category,jobs5)
        paginator = Paginator(jobs6,10)
        page_jobs = paginator.page(p)
        result_list = []
        for i in page_jobs:
            if i.wage1 == -1:
                wage = '薪资面议'
            else:
                wage = str(i.wage1)+'k-'+str(i.wage2)+'k'
            s = {'id':i.id,'job_title':i.job_title,'location':i.location,'wage':wage,'work_experience':i.work_experience,'education':i.education,'company_name':i.company_name}
            result_list.append(json.dumps(s))
        return JsonResponse({"msg":result_list,'num_page':paginator.num_pages,'page':int(p)})

def location_show(req):
    return render(req,'zhilianzhaopin/city.html')

def work_experience_show(req):
    return render(req, 'zhilianzhaopin/work_experience.html')

def education_show(req):
    return render(req, 'zhilianzhaopin/education.html')

def wordcloud_show(req):
    return render(req,'zhilianzhaopin/wordcloud.html')

def work_detail(req,n):
    job = Jobs.objects.get(id=n)
    if job.wage1 == -1:
        job.wage1 = '薪资面议'
    else:
        job.wage1 = str(job.wage1)+'k-'+str(job.wage2)+'k'
    return render(req,'zhilianzhaopin/work_detail.html',context={'msg':job})

class views(object):
    def __init__(self):
        self.coon = sqlite3.connect('db.sqlite3')
        self.df = pd.read_sql_query('select * from zhilianzhaopin_jobs',self.coon)

    def work_experience(self):
        '''
        生成工作经验图标
        :return:
        '''
        a = list(self.df[self.df['work_experience']!=''].loc[:,['work_experience']].groupby(['work_experience']).size())
        b =  self.df[self.df['work_experience']!=''].loc[:,['work_experience']].groupby(['work_experience']).size().index.values
        pie = Pie("工作经验饼状视图")
        pie.add("工作年限", b,a, is_label_show=True)
        pie.render('templates/zhilianzhaopin/work_experience.html')


    def education(self):
        '''
        生成学历图标
        :return:
        '''
        a = list(
            self.df[self.df['education'] != ''].loc[:, ['education']].groupby(['education']).size())
        b = self.df[self.df['education'] != ''].loc[:, ['education']].groupby(
            ['education']).size().index.values
        pie = Pie("学历要求饼状视图")
        pie.add("学历要求", b, a, is_label_show=True)
        pie.render('templates/zhilianzhaopin/education.html')

    def location(self):
        '''
        生成城市图表
        :return:
        '''
        a = list(self.df[self.df['location']!=''].loc[:,['location']].groupby(['location']).size())
        b =  list(self.df[self.df['location']!=''].loc[:,['location']].groupby(['location']).size().index.values)
        num = len(a)
        for i in range(num):
            if a[num - i - 1] < 20:
                a.pop(num - i -1)
                b.pop(num - i -1)
        bar=Bar('示例')
        bar.add('',b,a,is_label_show=True,is_datazoom_show=True)
        bar.use_theme('dark')
        bar.render(path='templates/zhilianzhaopin/city.html')

templates/layouts/master_blade.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    {% block title %}
    <title>OurSite</title>
    {% endblock title %}
    <meta charset="utf-8">
    {% block styles %}
    {% endblock %}
    {% block scripts %}
    {% endblock %}
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.2.2/jquery.form.min.js" integrity="sha384-FzT3vTVGXqf7wRfy8k4BiyzvbNfeYjK+frTVqZeNDFl8woCbF0CYG6g2fMEFFo/i" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<body>
    {# ************** navbar  ***************   #}
    {% include 'partials/navbar.html' %}
   
    <!-- *********** main container **************** -->
    <div class="container">
        {% block content %}
              <div class="col-md-6 col-md-offset-3" style="margin-top: 200px">
              <form action="/zhilianzhaopin/" method="post">
                  <div class="input-group">
                          <input type="text" class="form-control" placeholder="Search for..." name="kw">
                          <span class="input-group-btn">
        <button class="btn btn-default" type="submit">Go!</button>
      </span>

                  </div><!-- /input-group -->
                  {% csrf_token %}
               </form>
              </div><!-- /.col-lg-6 -->


        {% endblock content %}

    </div>
    {%  block foot %}
    {% include 'partials/footer.html' %}
    {% endblock %}
    {% block scripts_body %}
    {% endblock %}
 


</body>

</html>

templates/partials/footer.html
   <!-- ************* footer **********************-->

    <div class="container" style="margin-top: 200px">
        <hr/>
         &copy;{{ nowtime|date:'Y' }}, <a href="#">Fuboyang</a>
        <br/>
    </div>

templates/partials/navbar.html
<nav class="navbar navbar-inverse" style="border-radius: 0px;">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target=".navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">水恋鱼</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Analysis<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'zhilianzhaopin:location_show' %}">city</a></li>
                        <li><a href="{% url 'zhilianzhaopin:wordcloud_show' %}">key word</a></li>
                        <li><a href="{% url 'zhilianzhaopin:education_show' %}">Education</a></li>
                        <li><a href="{% url 'zhilianzhaopin:work_experience_show' %}">work experience</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">登录</a></li>
                <li><a href="#">注册</a></li>

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
</nav>

templates/zhilianzhaopin/work_detail.html
{% extends 'layouts/master_blade.html' %}
{% block content %}
    <div class="container" style="margin-top: 30px">
        <div class="col-md-2 col-md-offset-2 text-right"><span style="font-size: 18px"><b>职位名称：</b></span></div>
        <div class="col-md-8"><span style="font-size: 16px">{{ msg.job_title }}</span></div>
    </div>
    <br>
    <div class="container">
        <div class="col-md-2 col-md-offset-2 text-right"><span style="font-size: 18px"><b>公司名称：</b></span></div>
        <div class="col-md-8"><span style="font-size: 16px">{{ msg.company_name }}</span></div>
    </div>
    <br>
    <div class="container">
        <div class="col-md-2 col-md-offset-2 text-right"><span style="font-size: 18px"><b>职位月薪：</b></span></div>
        <div class="col-md-8"><span style="font-size: 16px">{{ msg.wage1 }}</span></div>
    </div>
    <br>
    <div class="container">
        <div class="col-md-2 col-md-offset-2 text-right"><span style="font-size: 18px"><b>工作地点：</b></span></div>
        <div class="col-md-8"><span style="font-size: 16px">{{ msg.location }}</span></div>
    </div>
    <br>
    <div class="container">
        <div class="col-md-2 col-md-offset-2 text-right"><span style="font-size: 18px"><b>工作经验：</b></span></div>
        <div class="col-md-8"><span style="font-size: 16px">{{ msg.work_experience }}</span></div>
    </div>
    <br>
    <div class="container">
        <div class="col-md-2 col-md-offset-2 text-right"><span style="font-size: 18px"><b>学历要求：</b></span></div>
        <div class="col-md-8"><span style="font-size: 16px">{{ msg.education }}</span></div>
    </div>
    <br>
    <div class="container">
        <div class="col-md-2 col-md-offset-2 text-right"><span style="font-size: 18px"><b>招聘人数：</b></span></div>
        <div class="col-md-8"><span style="font-size: 16px">{{ msg.recruits_number }}</span></div>
    </div>
    <br>
    <div class="container">
        <div class="col-md-2 col-md-offset-2 text-right"><span style="font-size: 18px"><b>职位类别：</b></span></div>
        <div class="col-md-8"><span style="font-size: 16px">{{ msg.job_categories }}</span></div>
    </div>
    <br>
    <div class="container">
        <div class="col-md-2 col-md-offset-2 text-right"><span style="font-size: 18px"><b>公司规模：</b></span></div>
        <div class="col-md-8"><span style="font-size: 16px">{{ msg.company_size }}</span></div>
    </div>
    <br>
    <div class="container">
        <div class="col-md-2 col-md-offset-2 text-right"><span style="font-size: 18px"><b>公司性质：</b></span></div>
        <div class="col-md-8"><span style="font-size: 16px">{{ msg.company_type }}</span></div>
    </div>
    <br>
    <div class="container">
        <div class="col-md-2 col-md-offset-2 text-right"><span style="font-size: 18px"><b>公司详细地址：</b></span></div>
        <div class="col-md-8"><span style="font-size: 16px">{{ msg.company_address }}</span></div>
    </div>
    <br>
    <div class="container">
        <div class="col-md-2 col-md-offset-2 text-right"><span style="font-size: 18px"><b>各种福利：</b></span></div>
        <div class="col-md-8"><span style="font-size: 16px">{{ msg.welfare_pos }}</span></div>
    </div>
    <br>

    <div class="container">
        <div class="col-md-2 col-md-offset-2 text-right"><span style="font-size: 18px"><b>职位信息：</b></span></div>
        <div class="col-md-8"><span style="font-size: 16px">{{ msg.job_description }}</span></div>
    </div>




{% endblock %}